project:
  type: website


website:
  title: "Espécies Exóticas Invasoras"
  favicon: img/favicon.png
  page-footer: 
    background: light
    center: |
      This page brought to you by <https://biodev.com.br>
    right: |
      This website was created with Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org) 
  navbar:
    background: light
    logo: img/leimac-logo.png
    logo-href: https://leimac.sites.ufsc.br/
    left:
      - href: index.qmd
        text: "Introdução"
      - href: mapa.qmd
        text: Mapa
      - about.qmd

format:
  html:
    css: styles.css
    toc: true
    theme: yeti
      # light:
      #  - cosmo
      #  - styles.scss

execute:
  freeze: auto


# margin-header: |
#   ![Logo image](/img/logo_udesc.png